DO
$$
    DECLARE
        PERSON_ID_VAL INTEGER := NEXTVAL('PERSON_ID_SEQ');
    BEGIN
        INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME)
        VALUES (PERSON_ID_VAL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ');

        INSERT INTO DOCUMENT(ID, DOCUMENT_TYPE, DOCUMENT_SERIES, DOCUMENT_NUMBER, PERSON_ID)
        VALUES (NEXTVAL('DOCUMENT_ID_SEQ'), 'PASSPORT', '0105', '456347772', PERSON_ID_VAL);
    END
$$;
